name: Docker Image for TCP Endpoint check exporter

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/**'

jobs:

  build:
    environment: maclucky
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          maclucky/tcp-endpoint-check-exporter
          ghcr.io/mac-lucky/tcp-endpoint-check-exporter

    - name: Get latest version tag from Docker Hub
      id: get_latest_version
      run: |
        LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/maclucky/tcp-endpoint-check-exporter/tags?page_size=100" | jq -r '.results[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Increment version
      id: increment_version
      run: |
        VERSION=${{ env.LATEST_TAG }}
        if [ -z "$VERSION" ]; then
          NEW_VERSION="1.0.0"
        else
          NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
        fi
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          maclucky/tcp-endpoint-check-exporter:${{ env.NEW_VERSION }}
          maclucky/tcp-endpoint-check-exporter:latest
          ghcr.io/mac-lucky/tcp-endpoint-check-exporter:${{ env.NEW_VERSION }}
          ghcr.io/mac-lucky/tcp-endpoint-check-exporter:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max