name: Docker Image for Kubernetes Ping Exporter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    environment: maclucky
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          maclucky/kubernetes-ping-exporter
          ghcr.io/mac-lucky/kubernetes-ping-exporter

    - name: Read version from file
      id: read_version
      run: |
        VERSION=$(cat version.txt)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Update version
      id: update_version
      run: |
        VERSION=$(cat version.txt)
        NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')
        echo $NEW_VERSION > version.txt
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          maclucky/kubernetes-ping-exporter:${{ env.NEW_VERSION }}
          maclucky/kubernetes-ping-exporter:latest
          ghcr.io/mac-lucky/kubernetes-ping-exporter:${{ env.NEW_VERSION }}
          ghcr.io/mac-lucky/kubernetes-ping-exporter:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Commit version update
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add version.txt
        git commit -m "Update version to ${{ env.NEW_VERSION }}"
        git push