name: Container Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build container
      run: docker build -t tcp-endpoint-check-exporter:test .

    - name: Create test config
      run: |
        mkdir -p test-config
        cat > test-config/config.yml <<EOF
        targets:
          - host: "google.com"
            port: 443
            alias: "search-engine"
          - host: "github.com"
            port: 443
            env: "test"
            alias: "code-repo"
          - host: "microsoft.com"
            port: 443
            alias: "msft"
          - host: "nonexistent.com"
            port: 443
            alias: "nonexistent.com"
        EOF

    - name: Run container
      run: |
        docker run -d \
          -p 2112:2112 \
          -v $(pwd)/test-config:/config \
          -e CHECK_INTERVAL_SECONDS=10 \
          tcp-endpoint-check-exporter:test

    - name: Wait for metrics
      run: sleep 15

    - name: Test metrics endpoint
      run: |
        response=$(curl -s http://localhost:2112/metrics)
        if echo "$response" | grep -q "tcp_endpoint_up"; then
          echo "✅ Metrics endpoint working"
          exit 0
        else
          echo "❌ Metrics endpoint not working"
          exit 1
        fi
